#(Use default files generated by Django startproject — no changes needed beyond paths.)
"""
ASGI config for e_notice_board project.

It exposes the ASGI callable as a module-level variable named ``application``.
"""

import os
from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'e_notice_board.settings')

application = get_asgi_application()
