#(Use default files generated by Django startproject — no changes needed beyond paths.)
"""
WSGI config for e_notice_board project.

It exposes the WSGI callable as a module-level variable named ``application``.
"""

import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'e_notice_board.settings')

application = get_wsgi_application()
